version: "3"

services:
  server:
    container_name: flask_project
    build:
      context: .
      dockerfile: ./backend.dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - postgres_db
      - couch_db
      - redis_db
    volumes:
      - .:/code

  migration:
    container_name: db_migration
    entrypoint: flask db migrate
    build:
      context: .
      dockerfile: ./backend.dockerfile
    depends_on:
      - postgres_db
    volumes:
      - .:/code

  upgrade:
    container_name: db_upgrade
    entrypoint: flask db upgrade
    build:
      context: .
      dockerfile: ./backend.dockerfile
    depends_on:
      - postgres_db
      - migration
    volumes:
      - .:/code


  postgres_db:
      container_name: postgres
      image: postgres:13
      restart: on-failure
      environment:
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: itservice
      expose:
        - 5432
      volumes:
        - postgres_storage:/var/lib/postgresql/data

  couch_db:
      container_name: couch
      image: couchdb:3.3
      restart: on-failure
      environment:
        COUCHDB_USER: alex   
        COUCHDB_PASSWORD: 12345 
        COUCHDB_SECRET: couchservice 
      expose:
        - 5984
      ports:
        - '7070:5984'
      volumes:
        - /opt/couchdb/data

  redis_db:
      container_name: redis
      image: redis:7
      restart: on-failure
      expose:
        - 6379


volumes:
  postgres_storage: