"""empty message

Revision ID: 18acb00c0126
Revises: 361740f8f88d
Create Date: 2023-01-09 18:09:07.958421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18acb00c0126'
down_revision = '361740f8f88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('Surname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Surname', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
